service: s3-azure-sync

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    AZURE_STORAGE_ACCOUNT: ${env:AZURE_STORAGE_ACCOUNT}
    AZURE_STORAGE_ACCESS_KEY: ${env:AZURE_STORAGE_ACCESS_KEY}
    S3_BUCKET: ${env:S3_BUCKET}

functions:
  s3Handler:
    handler: handler.s3Handler
    events:
      - s3:
          bucket: ${env:S3_BUCKET}
          event: s3:ObjectCreated:*
